RecipeCategory.create([{name: "Palacinke"}])
RecipeCategory.create([{name: "Torte"}])
RecipeCategory.create([{name: "Kolaci"}])
RecipeCategory.create([{name: "Salata"}])
RecipeCategory.create([{name: "Pasta"}])
RecipeCategory.create([{name: "Pizza"}])
RecipeCategory.create([{name: "Topla predjela"}])
RecipeCategory.create([{name: "Hladna predjela"}])
RecipeCategory.create([{name: "Rostilj"}])
RecipeCategory.create([{name: "Kuhana jela"}])
RecipeCategory.create([{name: "Plate"}])
RecipeCategory.create([{name: "Riba"}])
Ingredient.create([{ name:"Brasno", unit_price: 20, unit_quantity: 25, measurement_unit:"kg"}])
Ingredient.create([{ name:"Ulje", unit_price: 3, unit_quantity: 1, measurement_unit:"l"}])
Ingredient.create([{ name:"Vegeta", unit_price: 2, unit_quantity: 0.5, measurement_unit:"kg"}])
Ingredient.create([{ name:"Germa", unit_price: 1, unit_quantity: 0.5, measurement_unit:"kg"}])
Ingredient.create([{ name:"Nutela", unit_price: 10, unit_quantity: 5, measurement_unit:"kg"}])
Ingredient.create([{ name:"Mlijeko", unit_price: 2, unit_quantity: 1, measurement_unit:"l"}])
Ingredient.create([{ name:"Sol", unit_price: 2, unit_quantity: 1, measurement_unit:"kg"}])
Ingredient.create([{ name:"Biber", unit_price: 2, unit_quantity: 1, measurement_unit:"kg"}])
Ingredient.create([{ name:"Jaja", unit_price: 6, unit_quantity: 6, measurement_unit:"kom"}])
Ingredient.create([{ name:"Secer", unit_price: 2, unit_quantity: 1, measurement_unit:"kg"}])
Ingredient.create([{ name:"Dzem", unit_price: 5, unit_quantity: 1, measurement_unit:"kg"}])
User.create({name:"Test", email: "test@gmail.com", password: "test123"})